---
image:
  terraform:
    repository: hashicorp/terraform
    pullPolicy: IfNotPresent
    tag: "1.4.6"
  kubectl:
    repository: bitnami/kubectl
    pullPolicy: IfNotPresent
    tag: "1.26.5"

requiredVersion: "1.4.6"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

planner:
  schedule: "*/1 * * * *"  # Every Minute

netrc:
  create: false
  entries:
    - machine: ""
      login: ""
      password: ""

s3:
  enable: false
  entries:
    - profile: 
      accessKey:
      secretKey:
      region:
      version:

backend:
  type: kubernetes
  file: |
    secret_suffix     = "{{ include "tflauncher.fullname" . }}"
    in_cluster_config = true
    namespace         = "{{ .Release.Namespace }}"
module: 
  name: ""
  source: ""

modules: []

variables: []

outputs: []

tfvarsFile: ""

terraformrc: |
  default_backend = "kubernetes"

env: []

serviceAccount:
  createCluserAdmin: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
