---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tflauncher.fullname" . }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
data:
  {{- if .Values.netrc.create }}
  .netrc: {{ include "tflauncher.netrc" . | default "" | b64enc | quote }}
  {{- end }}
  .tfvars: {{ tpl .Values.tfvarsFile . | default "" | b64enc | quote }}
  backend.tf: {{ tpl .Values.backend.file . | default "" | b64enc | quote }}
  .terraformrc: {{ tpl .Values.terraformrc . | default "" | b64enc | quote }}
  .aws.config: {{ include "tflauncher.s3config" . | default "" | b64enc | quote }}
  .aws.credentials: {{ include "tflauncher.s3credentials" . | default "" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tflauncher.fullname" . }}-env
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
data:
  {{- range $env:= .Values.env }}
  {{- if $env.sensitive }}
  {{ $env.name | quote }}: {{ $env.value | default "" | b64enc | quote }}
  {{- end }}
  {{- end }}
