---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tflauncher.serviceAccountName" . }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# {{- if .Values.serviceAccount.createCluserAdmin -}}
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: {{ include "tflauncher.serviceAccountName" . }}
#   labels:
#     {{- include "tflauncher.labels" . | nindent 4 }}
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
# - kind: ServiceAccount
#   name: {{ include "tflauncher.serviceAccountName" . }}
#   namespace: {{ .Release.Namespace }}
# {{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tflauncher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tflauncher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tflauncher.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tflauncher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
