---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "tflauncher-test-integration.labels" . | nindent 4 }}
  name: {{ include "tflauncher-test-integration.fullname" . }}
type: Opaque
data:
  .htpasswd: {{ .Values.websrv.htpasswd | b64enc | quote }}
  accessKey: {{ .Values.minio.accessKey | b64enc | quote }}
  secretKey: {{ .Values.minio.secretKey | b64enc | quote }}
  minioUser: {{ .Values.mc.minioUser | b64enc | quote }}
  minioUserKey: {{ .Values.mc.minioUserKey | b64enc | quote }}
  pgPassword: {{ .Values.pg.password | b64enc | quote }}
