---
name: Create Test Chart
'on':
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["helm_charts/tflauncher-test-integration/**"]

env:
  REGISTRY: "ghcr.io" # GitHub Container Registry

jobs:
  module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
      - name: Package Chart
        run: |
          make test-chart-pkg
          helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
          helm push cache/tflauncher-test-integration-0.1.0.tgz oci://${{ env.REGISTRY }}/${{ github.actor }}
