---
name: Create Test Chart
'on':
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - helm_charts/tflauncher-test-integration/**
      - tests/test_integration_chart*.yml

env:
  REGISTRY: "ghcr.io" # GitHub Container Registry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v3

      - name: Package Chart
        run: make test-chart-pkg

      - uses: actions/upload-artifact@v3
        with:
          name: test-chart-pkg
          path: cache/tflauncher-test-integration-0.1.0.tgz
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1
      - uses: azure/setup-helm@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Setup Ansible
        run: pip install -r configs/requirements.txt

      - name: Retrieve saved Chart
        uses: actions/download-artifact@v2
        with:
          name: test-chart-pkg
          path: cache/tflauncher-test-integration-0.1.0.tgz

      - name: Setup Test Cluster
        uses: gacts/run-and-post-run@v1
        with:
          run: make kind-up
          post: make kind-down

      - name: Run Test
        run: ansible-playbook tests/cases/test_integration_chart.yml

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: azure/setup-helm@v3

      - name: Retrieve saved Helm Chart
        uses: actions/download-artifact@v2
        with:
          name: test-chart-pkg
          path: cache/tflauncher-test-integration-0.1.0.tgz

      - name: Publish Chart
        run: |
          helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
          helm push cache/tflauncher-test-integration-0.1.0.tgz oci://${{ env.REGISTRY }}/${{ github.actor }}
